// <auto-generated />
using LISTATAREFASAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LISTATAREFASAPI.Migrations
{
    [DbContext(typeof(ListaTarefasContext))]
    partial class ListaTarefasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LISTATAREFASAPI.Models.Tarefa", b =>
                {
                    b.Property<int>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarefaId"));

                    b.Property<bool>("Concluida")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDeTarefaId")
                        .HasColumnType("int");

                    b.HasKey("TarefaId");

                    b.HasIndex("TipoDeTarefaId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("LISTATAREFASAPI.Models.TipoDeTarefa", b =>
                {
                    b.Property<int>("TipoDeTarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDeTarefaId"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDeTarefaId");

                    b.ToTable("TiposDeTarefas");
                });

            modelBuilder.Entity("LISTATAREFASAPI.Models.Tarefa", b =>
                {
                    b.HasOne("LISTATAREFASAPI.Models.TipoDeTarefa", "TipoDeTarefa")
                        .WithMany()
                        .HasForeignKey("TipoDeTarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDeTarefa");
                });
#pragma warning restore 612, 618
        }
    }
}
